import type { ComponentType } from "react";
import {
  SiClaude,
  SiDocker,
  SiFigma,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGnubash,
  SiHuggingface,
  SiJavascript,
  SiJira,
  SiLangchain,
  SiNextdotjs,
  SiNodedotjs,
  SiNotion,
  SiNumpy,
  SiOpenai,
  SiPandas,
  SiPostgresql,
  SiPython,
  SiReact,
  SiScikitlearn,
  SiTerraform,
  SiTypescript,
} from "react-icons/si";
import {
  Binary,
  Cloud,
  Code2,
  FileText,
  ListChecks,
  MapPinned,
  MessageSquare,
  Search,
  Server,
  Users,
  Workflow,
} from "lucide-react";

export type TechIconComponent = ComponentType<{ className?: string }>;

/**
 * Shared map for skills grid, toolkit, and marquee (`key` matches data files).
 */
export const TECH_ICON_MAP: Record<string, TechIconComponent> = {
  azuredevops: Workflow,
  jira: SiJira,
  figma: SiFigma,
  notion: SiNotion,
  agile: ListChecks,
  aws: Cloud,
  azure: Server,
  terraform: SiTerraform,
  docker: SiDocker,
  githubactions: SiGithubactions,
  typescript: SiTypescript,
  javascript: SiJavascript,
  python: SiPython,
  sql: SiPostgresql,
  bash: SiGnubash,
  nextjs: SiNextdotjs,
  react: SiReact,
  nodejs: SiNodedotjs,
  openai: SiOpenai,
  rest: Code2,
  git: SiGit,
  github: SiGithub,
  scikitlearn: SiScikitlearn,
  pandas: SiPandas,
  numpy: SiNumpy,
  huggingface: SiHuggingface,
  langchain: SiLangchain,
  claude: SiClaude,
  roadmapping: MapPinned,
  prds: FileText,
  userresearch: Search,
  stakeholders: Users,
  promptengineering: MessageSquare,
  rag: Binary,
};

export const MARQUEE_TECH: { key: string; label: string }[] = [
  { key: "aws", label: "AWS" },
  { key: "azuredevops", label: "Azure DevOps" },
  { key: "terraform", label: "Terraform" },
  { key: "docker", label: "Docker" },
  { key: "githubactions", label: "GitHub Actions" },
  { key: "python", label: "Python" },
  { key: "typescript", label: "TypeScript" },
  { key: "javascript", label: "JavaScript" },
  { key: "react", label: "React" },
  { key: "nextjs", label: "Next.js" },
  { key: "langchain", label: "LangChain" },
  { key: "nodejs", label: "Node.js" },
  { key: "figma", label: "Figma" },
  { key: "openai", label: "OpenAI" },
];
